CREATE TABLE movies
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP                               NOT NULL,
    title        VARCHAR(255)                            NOT NULL,
    genre        VARCHAR(255)                            NOT NULL,
    release_year INT                                     NOT NULL,
    CONSTRAINT pk_movies PRIMARY KEY (id)
);

INSERT INTO movies(title, genre, release_year, created_at)
VALUES ('The Lord of the Rings: The Fellowship of the Ring', 'fantasy', 2001, NOW()),
       ('The Lord of the Rings: The Two Towers', 'fantasy', 2002, NOW()),
       ('The Lord of the Rings: The Return of the King', 'fantasy', 2003, NOW()),
       ('The Matrix', 'sci-fi', 1999, NOW()),
       ('Star Wars: Episode IV – A New Hope', 'science fiction', 1977, NOW());